# Jenkins — lab k3d: UI https://jenkins-npd.co (Ingress Traefik + Nginx SSL terminate)
# Shared Library + K8s cloud cấu hình thêm trong UI sau sync
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-jenkins
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-platform
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.7.14
    helm:
      releaseName: jenkins
      values: |
        controller:
          admin:
            password: "ChangeMe-Jenkins"
          jenkinsUrl: https://jenkins-npd.co/
          installPlugins:
            - kubernetes:4306.vc91e37ea_722d
            - workflow-aggregator:596.v8c21c963d92d
            - git:5.5.2
            - configuration-as-code:1932.v75cb_b_f812b_6
          JCasC:
            defaultConfig: true
          ingress:
            enabled: true
            hostName: jenkins-npd.co
            ingressClassName: traefik
            tls: []
          persistence:
            storageClass: local-path
            size: 8Gi
        agent:
          enabled: true
          kubernetes:
            namespace: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
