# Jenkins — lab k3d: UI https://jenkins-npd.co
# Chart 5.7.14 default image = 2.479.1 — PHẢI override controller.image.tag
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-jenkins
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-platform
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.7.27
    helm:
      releaseName: jenkins
      values: |
        persistence:
          enabled: true
          storageClass: local-path
          size: 8Gi
          accessMode: ReadWriteOnce
        controller:
          image:
            registry: docker.io
            repository: jenkins/jenkins
            tag: "lts-jdk17"
            pullPolicy: Always
          admin:
            password: "ChangeMe-Jenkins"
          jenkinsUrl: https://jenkins-npd.co/
          installLatestPlugins: false
          installPlugins:
            - kubernetes
            - workflow-aggregator
            - git
            - configuration-as-code
          overwritePlugins: true
          overwritePluginsFromImage: true
          initializeOnce: false
          podSecurityContextOverride:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            supplementalGroups: [1000]
          containerSecurityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 2Gi
          initContainerResources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 2Gi
          JCasC:
            defaultConfig: true
          ingress:
            enabled: true
            hostName: jenkins-npd.co
            ingressClassName: traefik
            tls: []
        agent:
          enabled: true
          kubernetes:
            namespace: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
