# HashiCorp Vault — lab k3d: UI https://vault-npd.co (dev mode, không dùng cho production)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-vault
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: banking-platform
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.1
    helm:
      releaseName: vault
      values: |
        server:
          ha:
            enabled: false
          dev:
            enabled: true
            devRootToken: "root"
          ingress:
            enabled: true
            ingressClassName: traefik
            activeService: true
            hosts:
              - host: vault-npd.co
                paths:
                  - /
            tls: []
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
