# Image tags — CI (Jenkins) cập nhật trên nhánh dev-k3d
# Registry lab k3d: harbor-npd.co

global:
  imageRegistry: harbor-npd.co/banking-demo
  imagePullSecrets:
    - name: harbor-registry

api-producer:
  image:
    repository: harbor-npd.co/banking-demo/api-producer
    tag: ae63979
    pullPolicy: Always

auth-service:
  image:
    repository: harbor-npd.co/banking-demo/auth-service
    tag: ae63979
    pullPolicy: Always

account-service:
  image:
    repository: harbor-npd.co/banking-demo/account-service
    tag: ae63979
    pullPolicy: Always

transfer-service:
  image:
    repository: harbor-npd.co/banking-demo/transfer-service
    tag: ae63979
    pullPolicy: Always

notification-service:
  image:
    repository: harbor-npd.co/banking-demo/notification-service
    tag: ae63979
    pullPolicy: Always

frontend:
  image:
    repository: harbor-npd.co/banking-demo/frontend
    tag: latest
    pullPolicy: Always
