# Biến môi trường GitOps — dev-ocp (OpenShift)
gitops:
  repoUrl: https://github.com/kevinram164/banking-demo.git
  branch: dev-ocp
  valuesImagesPath: phase9-gitops-platform/gitops/values-images.yaml

harbor:
  host: harbor-banking.apps.ocp01.npd.co
  project: banking-demo

jenkins:
  namespace: platform
  kanikoImage: gcr.io/kaniko-project/executor:v1.23.2

ci:
  watchPaths:
    - phase8-application-v3/**
    - phase9-gitops-platform/gitops/values-images.yaml
