# Linkerd control-plane — mTLS service mesh
# Identity TLS: phase9-gitops-platform/observability/certs/k3d-lab/ (Helm fileParameters)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-linkerd-control-plane
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    app.kubernetes.io/component: observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-platform
  sources:
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-control-plane
      targetRevision: 1.16.11
      helm:
        releaseName: linkerd-control-plane
        valueFiles:
          - $values/phase9-gitops-platform/observability/values-linkerd-k3d.yaml
        fileParameters:
          - name: identityTrustAnchorsPEM
            path: $values/phase9-gitops-platform/observability/certs/k3d-lab/ca.crt
          - name: identity.issuer.tls.crtPEM
            path: $values/phase9-gitops-platform/observability/certs/k3d-lab/issuer.crt
          - name: identity.issuer.tls.keyPEM
            path: $values/phase9-gitops-platform/observability/certs/k3d-lab/issuer.key
    - repoURL: https://github.com/kevinram164/banking-demo.git
      targetRevision: dev-k3d
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
