# PostgreSQL Exporter — Prometheus metrics cho Postgres (namespace banking)
# Dùng secret banking-db-secret (cùng với app). Apply: kubectl apply -f postgres-exporter.yaml
# Prometheus scrape target: postgres-exporter.banking.svc.cluster.local:9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: postgres
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          command:
            - /bin/sh
            - -c
            - |
              export DATA_SOURCE_NAME="postgresql://banking:bankingpass@postgres-postgresql-primary.postgres.svc.cluster.local:5432/banking?sslmode=disable"
              exec /bin/postgres_exporter
              #env:
              #- name: POSTGRES_USER
              #valueFrom:
              #  secretKeyRef:
              #    name: banking-db-secret
              #    key: POSTGRES_USER
              #- name: POSTGRES_PASSWORD
              #valueFrom:
              #  secretKeyRef:
              #    name: banking-db-secret
              #    key: POSTGRES_PASSWORD
              #- name: POSTGRES_DB
              #valueFrom:
              #  secretKeyRef:
              #    name: banking-db-secret
              #    key: POSTGRES_DB
          ports:
            - containerPort: 9187
              name: metrics
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: postgres
  labels:
    app: postgres-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: 9187
      name: metrics
  selector:
    app: postgres-exporter
