# Redis Exporter — Prometheus metrics cho Redis (namespace banking)
# Apply sau khi đã có Redis: kubectl apply -f redis-exporter.yaml
# Prometheus scrape target: redis-exporter.banking.svc.cluster.local:9121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          # Dùng Docker Hub thay quay.io (quay.io có thể unauthorized/rate-limit)
          image: oliver006/redis_exporter:v1.80.1
          args:
            - --redis.addr=redis.banking.svc.cluster.local:6379
          ports:
            - containerPort: 9121
              name: metrics
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app: redis-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics
  selector:
    app: redis-exporter
