{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking-demo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "banking-demo.frontend.fullname" . }}
    {{- include "banking-demo.frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "banking-demo.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: {{ .Values.frontend.service.portName }}
{{- end }}
