{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if (index .Values "api-producer").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-producer
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if (index .Values "auth-service").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if (index .Values "account-service").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if (index .Values "transfer-service").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transfer-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if (index .Values "notification-service").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if and (index .Values "shop-bridge") (index .Values "shop-bridge").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-bridge
  namespace: {{ .Release.Namespace }}
{{- end }}
