{{- $api := index .Values "api-producer" | default dict }}
{{- $auth := index .Values "auth-service" | default dict }}
{{- $acct := index .Values "account-service" | default dict }}
{{- $xfer := index .Values "transfer-service" | default dict }}
{{- $notif := index .Values "notification-service" | default dict }}
{{- $bridge := index .Values "shop-bridge" | default dict }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-producer
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $auth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $acct.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $xfer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transfer-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $notif.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: {{ .Release.Namespace }}
---
{{- end }}
{{- if $bridge.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-bridge
  namespace: {{ .Release.Namespace }}
{{- end }}
