{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
  labels:
    {{- include "banking-demo.labels" . | nindent 4 }}
    app.kubernetes.io/name: banking-demo
    phase: "2"
{{- end }}
