# Infrastructure Application: namespace, secret, postgres, redis
# Deploy đầu tiên trước các service khác
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-infra
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-demo
    app.kubernetes.io/component: infra
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy đầu tiên (infrastructure)
spec:
  project: banking-demo
  source:
    repoURL: https://github.com/kevinram164/banking-demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo
    helm:
      releaseName: banking-demo-infra
      valueFiles:
        - charts/common/values.yaml
        - charts/postgres/values.yaml
        - charts/redis/values.yaml
      parameters:
        - name: namespace.enabled
          value: "true"  # Tạo namespace "banking" (chỉ infra mới tạo)
        - name: secret.enabled
          value: "true"  # Tạo secret (chỉ infra mới tạo)
        - name: postgres.enabled
          value: "true"
        - name: redis.enabled
          value: "true"
        - name: kong.enabled
          value: "false"
        - name: auth-service.enabled
          value: "false"
        - name: account-service.enabled
          value: "false"
        - name: transfer-service.enabled
          value: "false"
        - name: notification-service.enabled
          value: "false"
        - name: frontend.enabled
          value: "false"
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false      # Không tự động xóa resources
      selfHeal: false   # Không tự động sửa drift
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
