apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-kong
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-demo
    app.kubernetes.io/component: kong
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-demo
  source:
    repoURL: https://github.com/kevinram164/banking-demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo
    helm:
      releaseName: banking-demo-kong
      valueFiles:
        - charts/common/values.yaml
        - charts/kong/values.yaml
      parameters:
        # QUAN TRỌNG: Disable namespace và secret để tránh conflict
        - name: namespace.enabled
          value: "false"  # Namespace đã được tạo bởi namespace.yaml
        - name: secret.enabled
          value: "false"  # Secret đã được tạo bởi namespace.yaml
        - name: postgres.enabled
          value: "false"
        - name: redis.enabled
          value: "false"
        - name: kong.enabled
          value: "true"
        - name: auth-service.enabled
          value: "false"
        - name: account-service.enabled
          value: "false"
        - name: transfer-service.enabled
          value: "false"
        - name: notification-service.enabled
          value: "false"
        - name: frontend.enabled
          value: "false"
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true   # Auto sync khi Kong config thay đổi — không ảnh hưởng postgres/redis
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
