# Notification Service Application
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-notification-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-demo
    app.kubernetes.io/component: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy sau kong (microservices)
spec:
  project: banking-demo
  source:
    repoURL: https://github.com/kevinram164/banking-demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo
    helm:
      releaseName: banking-demo-notification-service
      valueFiles:
        - charts/common/values.yaml
        - charts/notification-service/values.yaml
      parameters:
        - name: postgres.enabled
          value: "false"
        - name: redis.enabled
          value: "false"
        - name: kong.enabled
          value: "false"
        - name: auth-service.enabled
          value: "false"
        - name: account-service.enabled
          value: "false"
        - name: transfer-service.enabled
          value: "false"
        - name: notification-service.enabled
          value: "true"
        - name: frontend.enabled
          value: "false"
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
      # Không cần CreateNamespace=true vì namespace đã được tạo bởi infra (wave 0)
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
