# Notification Service Application
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-demo-notification-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-demo
    app.kubernetes.io/component: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy sau kong (microservices)
spec:
  project: banking-demo
  source:
    repoURL: https://github.com/kevinram164/banking-demo.git
    targetRevision: main
    path: phase2-helm-chart/banking-demo
    helm:
      releaseName: banking-demo-notification-service
      valueFiles:
        - charts/common/values.yaml
        - charts/notification-service/values.yaml
        - values-phase8.yaml  # v3 consumer, rabbitmqSecretRef (Phase 8)
      parameters:
        # QUAN TRỌNG: Disable namespace và secret để tránh conflict
        - name: namespace.enabled
          value: "false"  # Namespace đã được tạo bởi namespace.yaml
        - name: secret.enabled
          value: "false"  # Secret đã được tạo bởi namespace.yaml
        - name: postgres.enabled
          value: "false"
        - name: redis.enabled
          value: "false"
        - name: kong.enabled
          value: "false"
        - name: auth-service.enabled
          value: "false"
        - name: account-service.enabled
          value: "false"
        - name: transfer-service.enabled
          value: "false"
        - name: api-producer.enabled
          value: "false"  # Chỉ deploy notification-service, values-phase8 có api-producer.enabled=true
        - name: notification-service.enabled
          value: "true"
        - name: frontend.enabled
          value: "false"
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
