apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
      - "**"
  external_services:
    prometheus:
      url: "https://thanos-querier.openshift-monitoring.svc:9091"
      auth:
        type: bearer
        use_kiali_token: true
        insecure_skip_verify: true
      thanos_proxy:
        enabled: true
        url: "https://thanos-querier.openshift-monitoring.svc:9091"
        thanos_health_check_url: "https://thanos-querier.openshift-monitoring.svc:9091/api/v1/query?query=up"
    grafana:
      enabled: false
    tracing:
      enabled: false
