{{- $names := keys .Values.services | sortAlpha }}
{{- range $i, $name := $names }}
{{- $cfg := index $.Values.services $name }}
{{- if not $cfg.enabled }}{{ continue }}{- end }}
{{- if $i }}---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-{{ if eq $.Values.strategy "blueGreen" }}blue{{ else }}stable{{ end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    version: {{ if eq $.Values.strategy "blueGreen" }}blue{{ else }}stable{{ end }}
    {{- include "deployment-strategies.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $name }}
    version: {{ if eq $.Values.strategy "blueGreen" }}blue{{ else }}stable{{ end }}
  ports:
    - port: {{ $cfg.port }}
      targetPort: {{ $cfg.port }}
      name: {{ $cfg.portName | default "http" }}
{{ end }}
{{ print "\n" }}
