# Job import config declarative vào Kong DB
# Chạy SAU KHI Kong đã deploy và migrations đã xong
# Cách 1: kong config db_import (trực tiếp ghi DB)
# Cách 2: decK sync (qua Admin API) - cần Kong Admin đang chạy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: kong
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    services:
      - name: auth-service
        url: "http://auth-service.banking.svc.cluster.local:8001"
        routes:
          - name: auth-route
            paths: ["/api/auth"]
            strip_path: true
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "https://npd-banking.co", "http://npd-banking.co"]
              credentials: true
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Accept", "Accept-Version", "Content-Length", "Content-MD5", "Content-Type", "Date", "X-Session"]
      - name: account-service
        url: "http://account-service.banking.svc.cluster.local:8002"
        routes:
          - name: account-route
            paths: ["/api/account"]
            strip_path: true
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "https://npd-banking.co", "http://npd-banking.co"]
              credentials: true
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Accept", "Accept-Version", "Content-Length", "Content-MD5", "Content-Type", "Date", "X-Session", "X-Admin-Secret"]
      - name: transfer-service
        url: "http://transfer-service.banking.svc.cluster.local:8003"
        routes:
          - name: transfer-route
            paths: ["/api/transfer"]
            strip_path: true
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "https://npd-banking.co", "http://npd-banking.co"]
              credentials: true
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Accept", "Accept-Version", "Content-Length", "Content-MD5", "Content-Type", "Date", "X-Session"]
      - name: notification-service
        url: "http://notification-service.banking.svc.cluster.local:8004"
        routes:
          - name: notification-route
            paths: ["/api/notifications"]
            strip_path: true
          - name: notification-ws-route
            paths: ["/ws"]
            strip_path: false
            protocols: ["http", "https"]
        plugins:
          - name: cors
            config:
              origins: ["http://localhost:3000", "https://npd-banking.co", "http://npd-banking.co"]
              credentials: true
              methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
              headers: ["Accept", "Accept-Version", "Content-Length", "Content-MD5", "Content-Type", "Date", "X-Session"]
    plugins:
      - name: prometheus
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-config-import
  namespace: kong
  labels:
    app: kong-config-import
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: import
          image: kong:3.4
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "postgres-postgresql-primary.postgres.svc.cluster.local"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_DATABASE
              value: "kong"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "kongpass"
          command:
            - /bin/sh
            - -c
            - |
              kong config db_import /kong/kong.yml && echo "Import done"
          volumeMounts:
            - name: config
              mountPath: /kong
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kong-declarative-config
