# Giai đoạn 1: Secret cho DB và Redis (dùng stringData để rõ ràng khi demo)
apiVersion: v1
kind: Secret
metadata:
  name: banking-db-secret
  namespace: banking
type: Opaque
stringData:
  POSTGRES_USER: banking
  POSTGRES_PASSWORD: bankingpass
  POSTGRES_DB: banking
  DATABASE_URL: "postgresql://banking:bankingpass@postgres:5432/banking"
  REDIS_URL: "redis://redis:6379/0"
