# KEDA ScaledObject — account-service (Prometheus RPS)
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: account-service-scaler
  namespace: banking
spec:
  scaleTargetRef:
    name: account-service
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 120
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        # Loại trừ /health để tránh probe Kubernetes kích hoạt scale
        query: sum(rate(http_requests_total{job="account-service",endpoint!="/health"}[2m]))
        threshold: "5"
        activationThreshold: "1"
