# ArgoCD UI — upstream ArgoCD (ns argocd), OpenShift Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: phase9-gitops
    banking-demo/environment: dev-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  host: argocd-server-argocd.apps.ocp01.npd.co
  to:
    kind: Service
    name: argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
